export const Passages = [
  "Specialized uniforms, such as nun and priest garb, can be most helpful. Check out your local uniform store for a wide range of clothes that will get you in, and especially out, of all kinds of stores.",
  "It's enough for me to be sure that you and I exist at this moment.",
  "We've known each other for many years but this is the first time you've ever come to me for counsel or for help. I can't remember the last time you invited me to your house for a cup of coffee, even though my wife is Godmother to your only child. But, let's be frank here. You never wanted my friendship and you were afraid to be in my debt.",
  "The moon belongs to everyone; the best things in life are free. The stars belong to everyone; they gleam there for you and me. The flowers in spring, the robins that sing, the sunbeams that shine - they're yours, they're mine. And love can come to everyone - the best things in life are free!",
  "When the shoes first fell from the sky, he remembered thinking that destiny had struck him. Now he thought so again. It was more than a coincidence. It had to be destiny.",
  "Higher and higher he climbed. His strength came from somewhere deep inside himself and also seemed to come from the outside as well. After focusing on Big Thumb for so long, it was as if the rock had absorbed his energy and now acted like a kind of giant magnet pulling him toward it.",
  "We were playing checkers. I used to kid her once in a while because she wouldn't take her kings out of the back row. But I didn't kid her much though. You never wanted to kid Jane too much. I think I really like it best when you can kid the pants off a girl when the opportunity arises, but it's a funny thing. The girls I like best are ones I never feel much like kidding.",
  "In every war, there are calms between storms. There will be days when you lose faith in some of us, days when our allies turn against us, but the day will never come if we forsake this planet and its people.",
  "Say what you will. But a person just cannot know what he doesn't know. And you can't always see that a bad thing is going to happen before it happens. If you could, no bad would ever come.",
  "There are very few things I wish I could change about those two decades, but there are many things I wish I had known. I wish I had known, for instance, that such a long period of being single was in the cards for me. I also wish I'd known earlier that such a delay was not abnormal among my generation.",
  "I'd ask you about love, you'd probably quote me a sonnet. But you've never looked at a woman and been totally vulnerable. Known someone that could level you with her eyes, feeling like God put an angel on earth just for you.",
  "I'd been walking for hours and, as usual, I'd lost track of where I was, when I suddenly realized I'd reached the city limits. I immediately felt happy and, without hesitation, passed beyond the barrier and found myself walking between cultivated fields and meadows.",
  "Is this the real life? Is this just fantasy? Caught in a landslide, no escape from reality. Open your eyes, look up to the skies and see. I'm just a poor boy, I need no sympathy. Because I'm easy come, easy go, little high, little low. Any way the wind blows doesn't really matter to me.",
  'A Yoga master came to my office for a consult. I asked her to show me what made her pain worse. She sat on the floor in a pose fully twisting her spine, staying there for several minutes. It took her another few minutes to work through the pain to stand up. I stated, "I think I know what is causing your pain - doing that exercise."',
  "There was a time when I was alone, nowhere to go and no place to call home. My only friend was the man in the moon and even sometimes he would go away, too. Then one night, as I closed my eyes, I saw a shadow flying high. He came to me with the sweetest smile, told me he wanted to talk for a while.",
  "No matter what the world is, the god of that world creates the rules. In truth, you have been defeated by the rules I created. And as punishment for defying the God of the new world, you will die...",
  "There is no way that this winter is ever going to end as long as this groundhog keeps seeing his shadow. I don't see any other way out. He's got to be stopped. And I have to stop him.",
  "Let me photograph you in this light, in case it is the last time that we might be exactly like we were before we realized we were sad of getting old.",
  "There are many ways to get out; surrender is one, losing is another. Winning, cheating, which I don't recommend, but you have to do something. You have to have a strategy. See the number one rule in chess is this; whatever you do, don't play the other person's game. Play your own... Your move.",
  "We can't define consciousness because consciousness does not exist. Humans fancy that there's something special about the way we perceive the world, and yet we live in loops as tight and as closed as the hosts do, seldom questioning our choices, content, for the most part, to be told what to do next.",
  "The higher a man stands on the social ladder, the greater the number of people he is connected with, the more power he has over other people, the more obvious is the predestination and inevitability of his every action.",
  "Yes, Steve, I can tell you those things because when I said that we weren't releasing any information whatsoever I meant except his name, his address, his ethnicity, and what we think his motives are.",
  "I can tell you the license plate numbers of all six cars outside. I can tell you that our waitress is left-handed and the guy sitting up at the counter weighs two hundred and fifteen pounds and knows how to handle himself. I know the best place to look for a gun is the cab of the gray truck outside, and at this altitude, I can run flat out for a half mile before my hands start shaking. Now why would I know that? How can I know that and not know who I am?",
  "Seeing someone lose it like that. You know, it reminded me of how I feel sometimes. Like I'm on the verge of just blowing up. All the stress and pressure and anxiety just bubbling up. But I'm never able to let it out like that. You know, I just keep it inside.",
  "Perhaps the most valuable result of all education is the ability to make yourself do the thing you have to do, when it ought to be done, whether you like it or not; it is the first lesson that ought to be learned; and however early a man's training begins, it is probably the last lesson that he learns thoroughly.",
  "You know, back in the apartment, I suddenly felt like I didn't know you at all. It was as if you were a stranger. But how can that be true? I so vividly remember meeting you. I remember falling in love with you. I remember losing you.",
  "Anyway, like I was saying, shrimp is the fruit of the sea. You can barbecue it, boil it, broil it, bake it, saute it. There's shrimp-kabobs, shrimp creole, shrimp gumbo. Pan fried, deep fried, stir-fried.",
  "But sometimes illumination comes to our rescue at the very moment when all seems lost; we have knocked at every door and they open on nothing until, at last, we stumble unconsciously against the only one through which we can enter the kingdom we have sought in vain a hundred years - and it opens.",
  "Three hidden keys open three secret gates wherein the errant will be tested for worthy traits, and those with the skill to survive these straits will reach the end where the prize awaits",
  "Then you compared a woman's love to Hell, to barren land where water will not dwell, and you compared it to a quenchless fire, the more it burns the more is its desire to burn up everything that burnt can be. You say that just as worms destroy a tree a wife destroys her husband and contrives, as husbands know, the ruin of their lives.",
  "Even though the bell has rung, some of my classmates are still milling around on the ground. It's the first week of the second semester of senior year, and already they're acting as if they're almost done and out of here.",
];

export const CommonWords = [
  "the",
  "of",
  "and",
  "a",
  "to",
  "in",
  "is",
  "you",
  "that",
  "it",
  "he",
  "was",
  "for",
  "on",
  "are",
  "as",
  "with",
  "his",
  "they",
  "I",
  "at",
  "be",
  "this",
  "have",
  "from",
  "or",
  "one",
  "had",
  "by",
  "word",
  "but",
  "not",
  "what",
  "all",
  "were",
  "we",
  "when",
  "your",
  "can",
  "said",
  "there",
  "use",
  "an",
  "each",
  "which",
  "she",
  "do",
  "how",
  "their",
  "if",
  "will",
  "up",
  "other",
  "about",
  "out",
  "many",
  "then",
  "them",
  "these",
  "so",
  "some",
  "her",
  "would",
  "make",
  "like",
  "him",
  "into",
  "time",
  "has",
  "look",
  "two",
  "more",
  "write",
  "go",
  "see",
  "number",
  "no",
  "way",
  "could",
  "people",
  "my",
  "than",
  "first",
  "water",
  "been",
  "call",
  "who",
  "oil",
  "its",
  "now",
  "find",
  "long",
  "down",
  "day",
  "did",
  "get",
  "come",
  "made",
  "may",
  "part",
];
